src/Navcoin/Block/Entity/Vin.php
<?php

namespace App\Navcoin\Block\Entity;

class Vin
{
    /** @var string */
    private $coinbase;

    /** @var string */
    private $txId;

    /** @var int */
    private $vout;

    /** @var int */
    private $sequence;

    /** @var float */
    private $value = 0;

    /** @var int */
    private $valuesat = 0;

    /** @var PreviousOutput */
    private $previousOutput;

    /** @var string[] */
    private $addresses = [];

    public function __construct(
        ?string $coinbase,
        ?string $txId,
        ?int $vout,
        int $sequence,
        ?float $value,
        ?int $valuesat,
        ?PreviousOutput $previousOutput,
        ?array $addresses
    ){
        if ($coinbase != null) {
            $this->coinbase = $coinbase;
        }
        $this->txId = $txId;
        $this->vout = $vout;
        $this->sequence = $sequence;
        if ($value != null) {
            $this->value = $value;
        }
        if ($valuesat != null) {
            $this->valuesat = $valuesat;
        }
        if ($previousOutput != null) {
            $this->previousOutput = $previousOutput;
        }
        if ($addresses != null) {
            $this->addresses = $addresses;
        }
    }

    public function getCoinbase(): ?string
    {
        return $this->coinbase;
    }

    public function getTxId(): ?string
    {
        return $this->txId;
    }

    public function getVout(): ?int
    {
        return $this->vout;
    }

    public function getSequence(): int
    {
        return $this->sequence;
    }

    public function getValue(): float
    {
        return $this->value;
    }

    public function getValuesat(): int
    {
        return $this->valuesat;
    }

    public function getPreviousOutput(): ?PreviousOutput
    {
        return $this->previousOutput;
    }

    public function getAddresses(): array
    {
        return $this->addresses;
    }

    public function isPrivate(): bool
    {
        return $this->previousOutput != null && $this->previousOutput->isPrivate();
    }

    public function isPrivateFee(): bool
    {
        return $this->previousOutput != null && $this->previousOutput->isPrivate();
    }

    public function isWrapped(): bool
    {
        return $this->previousOutput != null && $this->previousOutput->isWrapped();
    }

    public function isMultiSig(): bool
    {
        return $this->previousOutput != null && $this->previousOutput->isMultiSig();
    }

}

src/Navcoin/Block/Entity/Vout.php
<?php

namespace App\Navcoin\Block\Entity;

class Vout
{
    /** @var string */
    private $type;

    /** @var int */
    private $index;

    /** @var float */
    private $amount;

    /** @var string[] */
    private $addresses = [];

    /** @var string */
    private $redeemedInTransaction;

    /** @var bool */
    private $redeemed;

    /** @var int */
    private $redeemedInBlock;

    /** @var string */
    private $hash;

    /** @var bool */
    private $private;

    /** @var bool */
    private $privateFee;

    /** @var MultiSig */
    private $multiSig;

    /** @var bool */
    private $wrapped;

    /** @var string[] */
    private $wrappedAddresses;

    public function __construct(string $type, int $index, float $amount, array $addresses, bool $redeemed, ?string $redeemedInTransaction, ?int $redeemedInBlock)
    {
        $this->type = $type;
        $this->index = $index;
        $this->amount = $amount != 0 ? $amount / 100000000 : 0;
        $this->addresses = $addresses;
        $this->redeemed = $redeemed;
        $this->redeemedInTransaction = $redeemedInTransaction;
        $this->redeemedInBlock = $redeemedInBlock;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getIndex(): int
    {
        return $this->index;
    }

    public function getAmount(): float
    {
        return $this->amount;
    }

    public function getAddress(): ?string
    {
        if (count($this->addresses) == 0) {
            return null;
        }

        return $this->addresses[0];
    }

    public function getAddresses(): array
    {
        return $this->addresses;
    }

    public function getRedeemedInTransaction(): ?string
    {
        return $this->redeemedInTransaction;
    }

    public function isRedeemed(): bool
    {
        return $this->redeemed;
    }

    public function getRedeemedInBlock(): ?int
    {
        return $this->redeemedInBlock;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function isPrivate(): bool
    {
        return $this->private ? true : false;
    }

    public function setPrivate(bool $private): void
    {
        $this->private = $private;
    }

    public function isPrivateFee(): bool
    {
        return $this->privateFee ? true : false;
    }

    public function setPrivateFee(bool $privateFee): void
    {
        $this->privateFee = $privateFee;
    }

    public function isMultiSig(): bool
    {
        return $this->multiSig != null;
    }

    public function getMultiSig(): ?MultiSig
    {
        return $this->multiSig;
    }

    public function setMultiSig(MultiSig $multiSig): void
    {
        $this->multiSig = $multiSig;
    }

    public function isWrapped(): bool
    {
        return $this->wrapped;
    }

    public function setWrapped(bool $wrapped): void
    {
        $this->wrapped = $wrapped;
    }

    public function getWrappedAddresses(): array
    {
        return $this->wrappedAddresses;
    }

    public function setWrappedAddresses(array $wrappedAddresses): void
    {
        $this->wrappedAddresses = $wrappedAddresses;
    }

    public function isCommunityFund(): bool
    {
        return in_array($this->getType(), ['PROPOSAL_YES_VOTE', 'PROPOSAL_NO_VOTE', 'PAYMENT_REQUEST_YES_VOTE', 'PAYMENT_REQUEST_NO_VOTE']);
    }

    public function isProposalVote(): bool
    {
        return in_array($this->getType(), ['PROPOSAL_YES_VOTE', 'PROPOSAL_NO_VOTE', 'PROPOSAL_ABSTAIN_VOTE', 'PROPOSAL_REMOVE_VOTE']);
    }

    public function isPaymentRequestVote(): bool
    {
        return in_array($this->getType(), ['PAYMENT_REQUEST_YES_VOTE', 'PAYMENT_REQUEST_NO_VOTE', 'PAYMENT_REQUEST_ABSTAIN_VOTE', 'PAYMENT_REQUEST_REMOVE_VOTE']);
    }

    public function isConsultationVote(): bool
    {
        return in_array($this->getType(), ['CONSULTATION_VOTE', 'CONSULTATION_VOTE_REMOVE', 'CONSULTATION_VOTE_ABSTENTION', 'DAO_SUPPORT', 'DAO_SUPPORT_REMOVE']);
    }

    public function isSupportVote(): bool
    {
        return in_array($this->getType(), ['DAO_SUPPORT', 'DAO_SUPPORT_REMOVE']);
    }
}

src/Controller/TransactionController.php
<?php

namespace App\Controller;

use App\Exception\TransactionNotFoundException;
use App\Navcoin\Block\Api\BlockApi;
use App\Navcoin\Block\Api\TransactionApi;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Throwable;

class TransactionController extends AbstractController
{
    /** @var int */
    private $pageSize = 10;

    /** @var BlockApi */
    private $blockApi;

    /** @var TransactionApi */
    private $transactionApi;

    public function __construct(BlockApi $blockApi, TransactionApi $transactionApi)
    {
        $this->blockApi = $blockApi;
        $this->transactionApi = $transactionApi;
    }

    /**
     * @Route("/txs/{type}/{includes}", defaults={"type"="all","includes"="all"})
     * @Template()
     */
    public function index(): array
    {
        return [];
    }

    /**
     * @Route("/tx.json")
     */
    public function transactions(Request $request, SerializerInterface $serializer): Response
    {
        $transactions = $this->transactionApi->getTransactions(
            $request->get('filters', []),
            $request->get('size', $this->pageSize),
            $request->get('page', 1)
        );

        return new Response($serializer->serialize($transactions, 'json'), 200, [
            'paginator' => $serializer->serialize($transactions->getPaginator(), 'json')
        ]);
    }

    /**
     * @Route("/tx/latest.json")
     */
    public function latest(Request $request, SerializerInterface $serializer): Response
    {
        try {
            $latestTxs = $this->transactionApi->getLatestTransactions($request->get('count'));
        } catch (Exception $e) {
            return new Response("Unable to load latest transactions", $e->getCode());
        }

        return new Response($serializer->serialize($latestTxs->getElements(), 'json'));
    }

    /**
     * @Route("/tx/{hash}")
     * @Template()
     */
    public function view(Request $request)
    {
        try {
            $transaction = $this->transactionApi->getTransaction($request->get('hash'));
            $block = $this->blockApi->getBlock($transaction->getHeight());
            $rawData = $this->transactionApi->getRawTransaction($transaction->getHash());
            $jsonData = json_decode($rawData, true);
            $strdzeel = $jsonData['strdzeel'];
        } catch(TransactionNotFoundException|Throwable $e) {
            return $this->render(
                'transaction/not_found.html.twig',
                ['hash' => $request->get('hash')],
                new Response(null, 404)
            );
        }

        return [
            'transaction' => $transaction,
            'block' => $block,
            'raw' => $rawData,
            'strdzeel' => $strdzeel,
        ];
    }
}

templates/transaction/components/index_transactions.html.twig
<div id="transaction-list">
    <div class="clearfix">
        <h1 class="float-left">Transactions</h1>
        <div class="table-total"></div>
    </div>

    <div class="table-filters"></div>
    <div class="table-pagination"></div>
    <table class="table table-striped table-adaptive table-nav table-bottom-stripe">
        <thead class="loading">
        <tr>
            <th>Type</th>
            <th>Hash</th>
            <th>Age</th>
            <th class="text-center">Height</th>
            <th class="text-center">Confirmations</th>
            <th>Value</th>
            <th>Fees</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
    <div class="table-pagination"></div>
</div>

templates/transaction/components/view_coinbase.html.twig
<h2>Coinbase</h2>

<table class="table table-striped table-adaptive table-nav">
    <thead>
    <tr>
        <th style="width: 5%">Index</th>
        <th style="width: 20%">Type</th>
        <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    {% for vout in transaction.vouts %}
        {% if vout.proposalVote %}
            <tr>
                <td data-role="index">{{ vout.index }}</td>
                <td data-role="type">{{ vout.type|capitalize|replace({'_': ' '}) }}</td>
                <td data-role="proposal" colspan="2">
                    <a class="break-word" href="{{ path('app_communityfund_view', {'hash': vout.hash}) }}">{{ vout.hash }}</a>
                </td>
            </tr>
        {% elseif vout.paymentRequestVote %}
            <tr>
                <td data-role="index">{{ vout.index }}</td>
                <td data-role="type">{{ vout.type|capitalize|replace({'_': ' '}) }}</td>
                <td data-role="proposal" colspan="2">
                    <a class="break-word" href="{{ path('app_communityfund_view', {'hash': vout.hash}) }}">{{ vout.hash }}</a>
                </td>
            </tr>
        {% elseif vout.consultationVote %}
            <tr>
                <td data-role="index">{{ vout.index }}</td>
                <td data-role="type">{{ vout.type|capitalize|replace({'_': ' '}) }}</td>
                <td data-role="proposal" colspan="2">
                    <a class="break-word" href="{{ path('app_dao_answer', {'hash': vout.hash}) }}">{{ vout.hash }}</a>
                </td>
            </tr>
        {% elseif vout.supportVote %}
            <tr>
                <td data-role="index">{{ vout.index }}</td>
                <td data-role="type">{{ vout.type|capitalize|replace({'_': ' '}) }}</td>
                <td data-role="proposal" colspan="2">
                    <a class="break-word" href="{{ path('app_dao_consultation', {'hash': vout.hash}) }}">{{ vout.hash }}</a>
                </td>
            </tr>
        {% elseif vout.type == "nonstandard" %}
            <tr>
                <td data-role="index">{{ vout.index }}</td>
                <td data-role="type" colspan="3">{{ vout.type|capitalize }}</td>
            </tr>
        {% else %}
            <tr>
                <td data-role="index">{{ vout.index }}</td>
                <td data-role="type">{{ vout.type|lower }}</td>
                <td data-role="address">
                    {% if vout.address %}
                        <a class="break-word" href="{{ path('app_address_index', {'hash': vout.address}) }}">{{ vout.address }}</a>
                    {% else %}
                        &nbsp;
                    {% endif %}
                </td>
                <td data-role="amount">{{ vout.amount|nav }}</td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

templates/transaction/components/view_inputs.html.twig
<div class="margin-bottom">
<h2>Inputs</h2>
<table class="table table-striped table-adaptive table-nav">
    <thead>
        <tr>
            <th class="text-center" style="width:5%">Index</th>
            <th style="width:10%">Type</th>
            {% if transaction.vins.hasMultiSig %}
                <th style="width:30%">Address</th>
                <th style="width:30%">MultiSig</th>
                <th style="width:10%">Previous Output</th>
            {% else %}
                <th style="width:40%">Address</th>
                <th style="width:30%">Previous Output</th>
            {% endif %}
            <th style="width: 15%" class="text-right">Amount</th>
        </tr>
    </thead>
    <tbody>
        {% for vin in transaction.vins.elements %}
            <tr>
                <td data-role="index" class="text-center">{{ vin.vout }}</td>
                <td data-role="type" >
                    {% if vin.isMultiSig %} MultiSig ({{ vin.previousOutput.multisig.required }}/{{ vin.previousOutput.multisig.total }})
                    {% elseif vin.isWrapped %} Wrapped
                    {% elseif vin.isPrivate %} Private
{#                    {% elseif vin.isPrivateFee %} Private Fee#}
                    {% elseif vin.previousOutput and vin.previousOutput.type == "pubkey" %} PubKey
                    {% elseif vin.previousOutput and vin.previousOutput.type == "pubkeyhash" %} PubKeyHash
                    {% elseif vin.previousOutput and vin.previousOutput.type =="nonstandard" %} NonStandard
                    {% elseif vin.previousOutput and vin.previousOutput.type =="cold_staking" %} ColdStaking
                    {% elseif vin.previousOutput and vin.previousOutput.type =="cold_stakin_v2" %} ColdStakingV2
                    {% elseif vin.previousOutput %} {{ vin.previousOutput.type }}
                    {% endif %}
                </td>
                <td data-role="address">
                    {% for address in vin.addresses %}
                        <span class="break-word">
                            <a href="{{ path('app_address_index', { 'hash': address }) }}">{{ address }}</a>
                        </span>
                    {% else %}
                        {% if vin.previousOutput.private %}Private{% endif %}
                    {% endfor %}
                </td>

                {% if vin.isMultiSig %}
                    <td data-role="multiSigs" class="break-word">
                        {% for signature in vin.previousOutput.multisig.signatures %}
                            {{ signature[0:30] }}...{{ signature[signature|length-6:] }}<br>
                        {% else %}
                            &nbsp;
                        {% endfor %}
                    </td>
                {% endif %}

                <td data-role="previousOutput">
                    {% if vin.previousOutput %}
                        <span style="white-space: nowrap">
                            <a href="{{ path('app_transaction_view', {'hash': vin.txid}) }}">
                                {{ vin.txid[0:10] }}...{{ vin.txid[vin.txid|length-4:] }}:{{ vin.vout }}
                            </a>
                            {% if vin.previousOutput.height %}
                                <br><small>Block <a href="{{ path('app_block_view', {'height': vin.previousOutput.height}) }}">{{ vin.previousOutput.height }}</a></small>
                            {% endif %}
                        </span>
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td data-role="amount" class="text-right">
                    {% if vin.previousOutput.wrapped %}
                        {{ vin.value|wnav }}
                    {% elseif vin.previousOutput.private %}
                        {{ vin.value|xnav }}
                    {% else %}
                        {{ vin.value|nav }}
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">There are no transaction inputs</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>

templates/transaction/components/view_outputs.html.twig
<div>
    <h2>Outputs</h2>

    <table class="table table-striped table-adaptive table-nav">
        <thead>
            <tr>
                <th style="width: 5%" class="text-center">Index</th>
                <th style="width: 10%">Type</th>
                {% if transaction.vouts.hasMultiSig %}
                    <th style="width:30%">Address</th>
                    <th style="width:30%">MultiSig</th>
                    <th style="width:10%">Redeemed&nbsp;In</th>
                {% else %}
                    <th style="width:40%">Address</th>
                    <th style="width:30%">Redeemed&nbsp;In</th>
                {% endif %}
                <th style="width: 15%" class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for key, vout in transaction.vouts %}
                <tr>
                    <td data-role="index" class="text-center">{{ vout.index }}</td>
                    <td data-role="type">
                        {% if vout.isMultiSig %} MultiSig ({{ vout.multisig.required }}/{{ vout.multisig.total }})
                        {% elseif vout.isWrapped %} Wrapped
                        {% elseif vout.isPrivate %} Private
                        {% elseif vout.isPrivateFee %} Private Fee
                        {% elseif vout.type == "PUBKEY" %} PubKey
                        {% elseif vout.type == "PUBKEYHASH" %} PubKeyHash
                        {% elseif vout.type == "NONSTANDARD" %} NonStandard
                        {% elseif vout.type == "CFUND_CONTRIBUTION" %} CfundContribution
                        {% elseif vout.type == "COLD_STAKING" %} ColdStaking
                        {% elseif vout.type == "COLD_STAKING_V2" %} ColdStakingV2
                        {% else %}
                            {{ vout.type }}
                        {% endif %}
                    </td>
                    <td data-role="address">
                        {% for address in vout.addresses %}
                            <span class="break-word">
                                <a href="{{ path('app_address_index', { 'hash': address }) }}">{{ address }}</a>
                            </span>
                        {% else %}
                            {% if vout.isPrivate %}
                                Private
                            {% elseif vout.isPrivateFee %}
                                <a href="{{ path('app_address_index', { 'hash': block.stakedBy }) }}">{{ block.stakedBy }}</a>
                            {% elseif vout.type == "NONSTANDARD" %}
                                NonStandard
                            {% else %} n/a
                            {% endif %}
                        {% endfor %}
                    </td>

                    {% if transaction.vouts.hasMultiSig %}
                        <td data-role="multiSigs" class="break-word">
                            {% if vout.multisig %}
                                {% for signature in vout.multisig.signatures %}
                                    {{ signature[0:30] }}...{{ signature[signature|length-6:] }}<br>
                                {% else %}
                                {% endfor %}
                            {% else %}
                                &nbsp;
                            {% endif %}
                        </td>
                    {% endif %}

                    <td data-role="redeemedIn">
                        {% if vout.redeemed and vout.redeemedInTransaction and vout.redeemedInBlock %}
                            <span style="white-space: nowrap">
                                <a href="{{ path('app_transaction_view', {'hash': vout.redeemedInTransaction}) }}">
                                    {{ vout.redeemedInTransaction[0:20] }}...{{ vout.redeemedInTransaction[vout.redeemedInTransaction|length-4:] }}
                                </a><br>
                                <small>Block <a href="{{ path('app_block_view', {'height': vout.redeemedInBlock}) }}">{{ vout.redeemedInBlock }}</a></small>
                            </span>
                        {% elseif vout.private == true %}
                            Unspent
                        {% elseif vout.type == 'CFUND_CONTRIBUTION' %}
                            Community&nbsp;Fund&nbsp;Contribution
                        {% else %}
                            Unspent
                        {% endif %}
                        {% if vout.isPrivateFee %}<br/><small>Private TX Fee</small>{% endif %}
                    </td>
                    <td data-role="amount" class="text-right">
                        {% if vout.wrapped %}
                            {{ vout.amount|wnav }}
                        {% elseif vout.private %}
                            {{ vout.amount|xnav }}
                        {% else %}
                            {{ vout.amount|nav }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

templates/transaction/components/view_raw_transaction.html.twig
<div class="card card-raw">
    <div class="card-body">
        <pre>{{ raw }}</pre>
    </div>
</div>

templates/transaction/components/view_summary.html.twig
<div class="row transaction-summary">
    <div class="col-sm-12 col-md-12 col-lg-8">
        <table class="table table-striped table-nav">
            <tbody>
                <tr>
                    <th>Hash</th>
                    <td class="text-right break-word">
                        {{ transaction.hash }}
                    </td>
                </tr>
                <tr>
                    <th>Height</th>
                    <td class="text-right">
                        <a href="{{ path('app_block_view', {'height': transaction.height}) }}">
                            {{ transaction.height|number_format }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Input</th>
                    <td class="text-right">
                        {{ transaction.vins.value|nav }}
                    </td>
                </tr>
                <tr>
                    <th>Output</th>
                    <td class="text-right">
                        {{ transaction.vouts.value|nav }}
                    </td>
                </tr>
                {% if transaction.staking %}
                    <tr>
                        <th>Stake&nbsp;Reward</th>
                        <td class="text-right">
                            {{ transaction.stake|nav }}
                        </td>
                    </tr>
                {% endif %}
                <tr>
                    <th>Fees Paid</th>
                    <td class="text-right">
                        {{ transaction.fees|nav }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="col-sm-12 col-md-12 col-lg-4">
        <table class="table table-striped table-nav table-second">
            <tbody>
                <tr>
                    <th>Confirmations</th>
                    <td class="text-right">{{ block.confirmations }}</td>
                </tr>
                <tr>
                    <th>Size</th>
                    <td class="text-right">{{ transaction.size }}</td>
                </tr>
                <tr>
                    <th>Version</th>
                    <td class="text-right">{{ transaction.version }}</td>
                </tr>
                <tr>
                    <th>Time</th>
                    <td class="text-right">
                        {{ transaction.time|date_localised('Y-m-d, H:i:s') }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>