src/Navcoin/SoftFork/Entity/SoftFork.php
<?php

namespace App\Navcoin\SoftFork\Entity;

use DateTime;

class SoftFork
{
    /** @var string */
    private $name;

    /** @var int */
    private $signalBit;

    /** @var string */
    private $state;

    /** @var DateTime */
    private $startTime;

    /** @var DateTime */
    private $timeout;

    /** @var int */
    private $lockedInHeight;

    /** @var int */
    private $activationHeight;

    /** @var int */
    private $signalHeight;

    /**
     * @var []string
     */
    private $cycles = [];

    public function __construct(
        String $name,
        int $signalBit,
        string $state,
        DateTime $startTime,
        DateTime $timeout,
        ?int $lockedInHeight,
        ?int $activationHeight,
        ?int $signalHeight
    ) {
        $this->name = $name;
        $this->signalBit = $signalBit;
        $this->state = $state;
        $this->startTime = $startTime;
        $this->timeout = $timeout;
        $this->lockedInHeight = $lockedInHeight;
        $this->activationHeight = $activationHeight;
        $this->signalHeight = $signalHeight;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getSignalBit(): int
    {
        return $this->signalBit;
    }

    public function getState(): string
    {
        return $this->state;
    }

    public function getStartTime(): DateTime
    {
        return $this->startTime;
    }

    public function getTimeout(): DateTime
    {
        return $this->timeout;
    }

    public function getLockedInHeight(): ?int
    {
        return $this->lockedInHeight;
    }

    public function getActivationHeight(): ?int
    {
        return $this->activationHeight;
    }

    public function getSignalHeight(): int
    {
        return $this->signalHeight;
    }

    public function addCycle(int $index, int $blocks) {
        $this->cycles[$index] = $blocks;
    }

    public function getBestCycle(): int {
        return count($this->cycles) > 0 ? end($this->cycles) : 0;
    }

    public function isSignalling(): bool {
        return in_array($this->state, ["defined", "started"]) && $this->timeout->getTimestamp() >= (new DateTime())->getTimestamp();
    }

    public function isActive(): bool {
        return in_array($this->state, ["active", "locked_in"]);
    }

    public function isExpired(): bool {
        return in_array($this->state, ["defined", "started"]) && $this->timeout->getTimestamp() < (new DateTime())->getTimestamp();
    }
}

src/Navcoin/SoftFork/Entity/SoftForkCycle.php
<?php

namespace App\Navcoin\SoftFork\Entity;

class SoftForkCycle
{
    /**
     * @var int
     */
    private $blocksInCycle;

    /**
     * @var int
     */
    private $blockCycle;

    /**
     * @var int
     */
    private $currentBlock;

    /**
     * @var int
     */
    private $firstBlock;

    /**
     * @var int
     */
    private $remainingBlocks;

    public function __construct(int $blocksInCycle, int $blockCycle, int $currentBlock, int $firstBlock, int $remainingBlocks)
    {
        $this->blocksInCycle = $blocksInCycle;
        $this->blockCycle = $blockCycle;
        $this->currentBlock = $currentBlock;
        $this->firstBlock = $firstBlock;
        $this->remainingBlocks = $remainingBlocks;
    }

    public function getBlocksInCycle(): int
    {
        return $this->blocksInCycle;
    }

    public function getBlockCycle(): int
    {
        return $this->blockCycle;
    }

    public function getCurrentBlock(): int
    {
        return $this->currentBlock;
    }

    public function getFirstBlock(): int
    {
        return $this->firstBlock;
    }

    public function getRemainingBlocks(): int
    {
        return $this->remainingBlocks;
    }
}

src/Navcoin/SoftFork/Entity/SoftForks.php
<?php

namespace App\Navcoin\SoftFork\Entity;

use App\Navcoin\Common\Entity\IteratorEntity;
use App\Navcoin\Common\Entity\IteratorEntityInterface;
use App\Navcoin\Common\Entity\Paginated;
use App\Navcoin\SoftFork\Exception\SoftForkNotFoundException;

class SoftForks extends IteratorEntity implements IteratorEntityInterface
{
    use Paginated;

    public function setSupportedTypes()
    {
        $this->supportedTypes = [SoftFork::class];
    }

    public function sortByLockedInHeight() {
        $softForks = $this->getElements();
        usort($softForks, function (SoftFork $a, SoftFork $b) {
            return -1 * ($a->getLockedInHeight() - $b->getLockedInHeight());
        });

        $this->setElements($softForks);
    }
}

src/Controller/SoftForkController.php
<?php

namespace App\Controller;

use App\Navcoin\Block\Api\BlockApi;
use App\Navcoin\SoftFork\Api\SoftForkApi;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Routing\Annotation\Route;

class SoftForkController
{
    /**
     * @Route("/soft-forks")
     * @Template()
     */
    public function index(SoftForkApi $softForkApi, BlockApi $blockApi)
    {
        $softForks = $softForkApi->getAll();
        $softForks->sortByLockedInHeight();

        return [
            'cycle' => $softForkApi->getCycle(),
            'block' => $blockApi->getBestBlock(),
            'softForks' => $softForks,
        ];
    }
}

templates/soft_fork/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Soft Forks{% endblock %}
{% block description %}Soft forks that have been proposed and activated on the Navcoin network{% endblock %}

{% block page %}page-soft-forks-index{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Soft Forks</h1>

                <div class="alert alert-info">
                    Signaling for block <strong>{{ (cycle.currentBlock-cycle.firstBlock)|number_format }}</strong> of <strong>{{ cycle.blocksInCycle|number_format }}</strong> in the {{ cycle.blockCycle|ordinal }} block cycle.<br/>
                    There are <strong>{{ cycle.remainingBlocks|number_format }}</strong> blocks remaining.
                </div>
            </div>
        </div>

        <div class="row margin-bottom">
            <div class="col-sm-12 col-md-6">
                <h2>Active / Locked-in</h2>
                <table class="table table-striped table-nav margin-bottom">
                    <thead>
                    <tr>
                        <td>Name</td>
                        <td class="text-center">Locked In Height</td>
                        <td class="text-center">Activation Height</td>
                        <td class="text-center">Votes</td>
                        <td class="text-center">Status</td>
                    </tr>
                    </thead>
                    <tbody>

                    {% for fork in softForks|filter(fork => fork.active) %}
                        <tr>
                            <td>{{ fork.name|replace({"_": " "})|capitalize }}</td>
                            <td class="text-center">
                                <a href="{{ path('app_block_view', {'height': fork.lockedInHeight }) }}">{{ fork.lockedInHeight }}</a>
                            </td>
                            <td class="text-center">
                                {% if fork.state == 'ACTIVE' %}
                                    <a href="{{ path('app_block_view', {'height': fork.activationHeight }) }}">{{ fork.activationHeight }}</a>
                                {% else %}
                                    {% if block.height < fork.activationHeight %}
                                        {{ fork.activationHeight }}
                                    {% else %}
                                        <a href="{{ path('app_block_view', {'height': fork.activationHeight }) }}">
                                            {{ fork.activationHeight }}
                                        </a>
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {{ ((fork.bestCycle / cycle.blocksInCycle) * 100)|number_format(1) }}%
                            </td>
                            <td class="text-center">
                                {% if fork.state == 'active' %}
                                    <span class="badge badge-success">{{ fork.state|capitalize }}</span>
                                {% elseif fork.state == 'locked_in' %}
                                    <span class="badge badge-info">Locked In</span>
                                {% else %}
                                    <span class="badge badge-info">{{ fork.state|capitalize }}</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-sm-12 col-md-6">
                <h2>Signalling</h2>
                <table class="table table-striped table-nav margin-bottom">
                    <thead>
                    <tr>
                        <td>Name</td>
                        <td class="text-center">Blocks Signalling</td>
                        <td class="text-center d-none d-sm-table-cell">Blocks Required</td>
                        <td class="text-center d-none d-sm-table-cell">Blocks Remaining</td>
                        <td class="text-center">Votes</td>
                        <td class="text-center">Status</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for fork in softForks|filter(fork => fork.signalling) %}
                        <tr>
                            <td>{{ fork.name|replace({"_": " "})|capitalize }}</td>
                            <td class="text-center">{{ fork.bestCycle|number_format }}</td>
                            <td class="text-center d-none d-sm-table-cell">{{ (cycle.blocksInCycle * 0.75)|number_format }}</td>
                            <td class="text-center d-none d-sm-table-cell">{{ cycle.remainingBlocks|number_format }}</td>
                            <td class="text-center">{{ ((fork.bestCycle / (cycle.blocksInCycle-cycle.remainingBlocks)) * 100)|number_format(1) }}%</td>
                            <td class="text-center">
                                {% if (cycle.blocksInCycle * 0.75) - fork.bestCycle > cycle.remainingBlocks %}
                                    <span class="badge badge-warning">Missed</span>
                                {% elseif (fork.bestCycle >= (cycle.blocksInCycle * 0.75)) %}
                                    <span class="badge badge-info">Locked In</span>
                                {% else %}
                                    <span class="badge badge-info">{{ fork.state|capitalize }}</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6" class="text-center">There are no signalling soft forks</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <h2>Expired</h2>
                <table class="table table-striped table-nav margin-bottom">
                    <thead>
                    <tr>
                        <td>Name</td>
                        <td class="text-center">Start Time</td>
                        <td class="text-center">Timeout</td>
                        <td class="text-center">Status</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for fork in softForks|filter(fork => fork.expired) %}
                        <tr>
                            <td>{{ fork.name }}</td>
                            <td class="text-center">{{ fork.startTime|date_localised('Y-m-d, H:i:s') }}</td>
                            <td class="text-center">{{ fork.timeout|date_localised('Y-m-d, H:i:s') }}</td>
                            <td class="text-center"><span class="badge badge-danger">Expired</span></td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="4" class="text-center">There are no expired soft forks</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}