src/Navcoin/Block/Entity/Vout.php
<?php

namespace App\Navcoin\Block\Entity;

class Vout
{
    /** @var string */
    private $type;

    /** @var int */
    private $index;

    /** @var float */
    private $amount;

    /** @var string[] */
    private $addresses = [];

    /** @var string */
    private $redeemedInTransaction;

    /** @var bool */
    private $redeemed;

    /** @var int */
    private $redeemedInBlock;

    /** @var string */
    private $hash;

    /** @var bool */
    private $private;

    /** @var bool */
    private $privateFee;

    /** @var MultiSig */
    private $multiSig;

    /** @var bool */
    private $wrapped;

    /** @var string[] */
    private $wrappedAddresses;

    public function __construct(string $type, int $index, float $amount, array $addresses, bool $redeemed, ?string $redeemedInTransaction, ?int $redeemedInBlock)
    {
        $this->type = $type;
        $this->index = $index;
        $this->amount = $amount != 0 ? $amount / 100000000 : 0;
        $this->addresses = $addresses;
        $this->redeemed = $redeemed;
        $this->redeemedInTransaction = $redeemedInTransaction;
        $this->redeemedInBlock = $redeemedInBlock;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getIndex(): int
    {
        return $this->index;
    }

    public function getAmount(): float
    {
        return $this->amount;
    }

    public function getAddress(): ?string
    {
        if (count($this->addresses) == 0) {
            return null;
        }

        return $this->addresses[0];
    }

    public function getAddresses(): array
    {
        return $this->addresses;
    }

    public function getRedeemedInTransaction(): ?string
    {
        return $this->redeemedInTransaction;
    }

    public function isRedeemed(): bool
    {
        return $this->redeemed;
    }

    public function getRedeemedInBlock(): ?int
    {
        return $this->redeemedInBlock;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function isPrivate(): bool
    {
        return $this->private ? true : false;
    }

    public function setPrivate(bool $private): void
    {
        $this->private = $private;
    }

    public function isPrivateFee(): bool
    {
        return $this->privateFee ? true : false;
    }

    public function setPrivateFee(bool $privateFee): void
    {
        $this->privateFee = $privateFee;
    }

    public function isMultiSig(): bool
    {
        return $this->multiSig != null;
    }

    public function getMultiSig(): ?MultiSig
    {
        return $this->multiSig;
    }

    public function setMultiSig(MultiSig $multiSig): void
    {
        $this->multiSig = $multiSig;
    }

    public function isWrapped(): bool
    {
        return $this->wrapped;
    }

    public function setWrapped(bool $wrapped): void
    {
        $this->wrapped = $wrapped;
    }

    public function getWrappedAddresses(): array
    {
        return $this->wrappedAddresses;
    }

    public function setWrappedAddresses(array $wrappedAddresses): void
    {
        $this->wrappedAddresses = $wrappedAddresses;
    }

    public function isCommunityFund(): bool
    {
        return in_array($this->getType(), ['PROPOSAL_YES_VOTE', 'PROPOSAL_NO_VOTE', 'PAYMENT_REQUEST_YES_VOTE', 'PAYMENT_REQUEST_NO_VOTE']);
    }

    public function isProposalVote(): bool
    {
        return in_array($this->getType(), ['PROPOSAL_YES_VOTE', 'PROPOSAL_NO_VOTE', 'PROPOSAL_ABSTAIN_VOTE', 'PROPOSAL_REMOVE_VOTE']);
    }

    public function isPaymentRequestVote(): bool
    {
        return in_array($this->getType(), ['PAYMENT_REQUEST_YES_VOTE', 'PAYMENT_REQUEST_NO_VOTE', 'PAYMENT_REQUEST_ABSTAIN_VOTE', 'PAYMENT_REQUEST_REMOVE_VOTE']);
    }

    public function isConsultationVote(): bool
    {
        return in_array($this->getType(), ['CONSULTATION_VOTE', 'CONSULTATION_VOTE_REMOVE', 'CONSULTATION_VOTE_ABSTENTION', 'DAO_SUPPORT', 'DAO_SUPPORT_REMOVE']);
    }

    public function isSupportVote(): bool
    {
        return in_array($this->getType(), ['DAO_SUPPORT', 'DAO_SUPPORT_REMOVE']);
    }
}

src/Navcoin/CommunityFund/Entity/BlockCycle.php
<?php

namespace App\Navcoin\CommunityFund\Entity;

class BlockCycle
{
    /**
     * @var int
     */
    private $blocksInCycle;

    /**
     * @var float
     */
    private $minQuorum;

    /**
     * @var BlockCycleVoting
     */
    private $proposalVoting;

    /**
     * @var BlockCycleVoting
     */
    private $paymentVoting;

    /**
     * @var int
     */
    private $height;

    /**
     * @var int
     */
    private $cycle;

    /**
     * @var int
     */
    private $firstBlock;

    /**
     * @var int
     */
    private $currentBlock;

    public function __construct(
        int $blocksInCycle,
        BlockCycleVoting $proposalVoting,
        BlockCycleVoting $paymentVoting,
        int $height,
        int $cycle,
        int $firstBlock,
        int $currentBlock
    ) {
        $this->blocksInCycle = $blocksInCycle;
        $this->proposalVoting = $proposalVoting;
        $this->paymentVoting = $paymentVoting;
        $this->height = $height;
        $this->cycle = $cycle;
        $this->firstBlock = $firstBlock;
        $this->currentBlock = $currentBlock;
    }

    public function getBlocksInCycle(): int
    {
        return $this->blocksInCycle;
    }

    public function getProposalVoting(): BlockCycleVoting
    {
        return $this->proposalVoting;
    }

    public function getPaymentVoting(): BlockCycleVoting
    {
        return $this->paymentVoting;
    }

    public function getHeight(): int
    {
        return $this->height;
    }

    public function getCycle(): int
    {
        return $this->cycle;
    }

    public function getFirstBlock(): int
    {
        return $this->firstBlock;
    }

    public function getCurrentBlock(): int
    {
        return $this->currentBlock;
    }

    public function getRemainingBlocks(): int
    {
        return $this->blocksInCycle - $this->currentBlock;
    }
}

src/Navcoin/CommunityFund/Entity/BlockCycleVoting.php
<?php

namespace App\Navcoin\CommunityFund\Entity;

class BlockCycleVoting
{
    /**
     * @var int
     */
    private $cycles;

    /**
     * @var float
     */
    private $accept;

    /**
     * @var float
     */
    private $reject;

    /**
     * @var float
     */
    private $quorum;

    public function __construct(int $cycles, float $accept, float $reject, float $quorum)
    {
        $this->cycles = $cycles;
        $this->accept = $accept;
        $this->reject = $reject;
        $this->quorum = $quorum;
    }

    public function getCycles(): int
    {
        return $this->cycles;
    }

    public function getAccept(): float
    {
        return $this->accept;
    }

    public function getReject(): float
    {
        return $this->reject;
    }

    public function getQuorum(): float
    {
        return $this->quorum;
    }
}

src/Navcoin/CommunityFund/Entity/PaymentRequest.php
<?php

namespace App\Navcoin\CommunityFund\Entity;

class PaymentRequest
{
    /** @var int */
    private $version;

    /** @var string */
    private $hash;

    /** @var string */
    private $blockHash;

    /** @var string */
    private $proposalHash;

    /** @var string */
    private $description;

    /** @var float */
    private $requestedAmount;

    /** @var string */
    private $state;

    /** @var string */
    private $stateChangedOnBlock;

    /** @var string */
    private $status;

    /** @var string */
    private $paidOnBlock;

    /** @var int */
    private $votesYes;

    /** @var int */
    private $votesAbs;

    /** @var int */
    private $votesNo;

    /** @var int */
    private $votesExcluded;

    /** @var int */
    private $votingCycle;

    public function __construct(
        int $version,
        string $hash,
        string $blockHash,
        string $proposalHash,
        string $description,
        float $requestedAmount,
        string $state,
        ?string $stateChangedOnBlock,
        string $status,
        int $votesYes,
        int $votesAbs,
        int $votesNo,
        int $votesExcluded,
        int $votingCycle
    ) {
        $this->version = $version;
        $this->hash = $hash;
        $this->blockHash = $blockHash;
        $this->proposalHash = $proposalHash;
        $this->description = $description;
        $this->requestedAmount = $requestedAmount;
        $this->state = $state;
        $this->stateChangedOnBlock = $stateChangedOnBlock;
        $this->status = $status;
        $this->votesYes = $votesYes;
        $this->votesAbs = $votesAbs;
        $this->votesNo = $votesNo;
        $this->votesExcluded = $votesExcluded;
        $this->votingCycle = $votingCycle;
    }

    public function getVersion(): int
    {
        return $this->version;
    }

    public function getHash(): string
    {
        return $this->hash;
    }

    public function getBlockHash(): string
    {
        return $this->blockHash;
    }

    public function getProposalHash(): string
    {
        return $this->proposalHash;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function getRequestedAmount(): float
    {
        return $this->requestedAmount;
    }

    public function getState(): string
    {
        return $this->state;
    }

    public function getStateChangedOnBlock(): string
    {
        return $this->stateChangedOnBlock;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function getPaidOnBlock(): ?string
    {
        if ($this->paidOnBlock == "0000000000000000000000000000000000000000000000000000000000000000") {
            return null;
        }

        return $this->paidOnBlock;
    }

    public function setPaidOnBlock(string $paidOnBlock): self
    {
        $this->paidOnBlock = $paidOnBlock;

        return $this;
    }

    public function getVotesYes(): int
    {
        return $this->votesYes;
    }

    public function getVotesAbs(): int
    {
        return $this->votesAbs;
    }

    public function getVotesNo(): int
    {
        return $this->votesNo;
    }

    public function getVotesExcluded(): int
    {
        return $this->votesExcluded;
    }

    public function getVotingCycle(): int
    {
        return $this->votingCycle;
    }

    public function getIsSuper(): bool
    {
        return $this->version & 1<<5;
    }
}

src/Navcoin/CommunityFund/Entity/PaymentRequestVote.php
<?php

namespace App\Navcoin\CommunityFund\Entity;

class PaymentRequestVote
{
    /**
     * @var int
     */
    private $votesYes;

    /**
     * @var int
     */
    private $votesNo;

    /**
     * @var int
     */
    private $votingCycle;

    public function __construct(int $votesYes, int $votesNo, int $votingCycle)
    {
        $this->votesYes = $votesYes;
        $this->votesNo = $votesNo;
        $this->votingCycle = $votingCycle;
    }

    public function getVotesYes(): int
    {
        return $this->votesYes;
    }

    public function getVotesNo(): int
    {
        return $this->votesNo;
    }

    public function getVotesTotal(): int
    {
        return $this->votesYes + $this->votesNo;
    }

    public function getVotingCycle(): int
    {
        return $this->votingCycle;
    }
}

src/Navcoin/CommunityFund/Entity/Proposal.php
<?php

namespace App\Navcoin\CommunityFund\Entity;

class Proposal
{
    /** @var int */
    private $version;

    /** @var string */
    private $hash;

    /** @var string */
    private $blockHash;

    /** @var integer */
    private $height;

    /** @var string */
    private $description;

    /** @var float */
    private $requestedAmount;

    /** @var float */
    private $notYetPaid;

    /** @var float */
    private $userPaidFee;

    /** @var string */
    private $paymentAddress;

    /** @var int */
    private $proposalDuration;

    /** @var string */
    private $state;

    /** @var string */
    private $stateChangedOnBlock;

    /** @var string */
    private $status;

    /** @var \DateTime */
    private $createdAt;

    /** @var \DateTime */
    private $expiresOn;

    /** @var int */
    private $votesYes;

    /** @var int */
    private $votesAbs;

    /** @var int */
    private $votesNo;

    /** @var int */
    private $votesExcluded;

    /** @var int */
    private $votingCycle;

    public function __construct(
        int $version,
        string $hash,
        string $blockHash,
        int $height,
        string $description,
        float $requestedAmount,
        float $notYetPaid,
        float $userPaidFee,
        string $paymentAddress,
        int $proposalDuration,
        string $state,
        ?string $stateChangedOnBlock,
        string $status,
        int $votesYes,
        int $votesAbs,
        int $votesNo,
        int $votesExcluded,
        int $votingCycle
    ) {
        $this->version = $version;
        $this->hash = $hash;
        $this->blockHash = $blockHash;
        $this->height = $height;
        $this->description = $description;
        $this->requestedAmount = $requestedAmount;
        $this->notYetPaid = $notYetPaid;
        $this->userPaidFee = $userPaidFee;
        $this->paymentAddress = $paymentAddress;
        $this->proposalDuration = $proposalDuration;
        $this->state = $state;
        $this->stateChangedOnBlock = $stateChangedOnBlock;
        $this->status = $status;
        $this->votesYes = $votesYes;
        $this->votesAbs = $votesAbs;
        $this->votesNo = $votesNo;
        $this->votesExcluded = $votesExcluded;
        $this->votingCycle = $votingCycle;
    }

    public function getVersion(): int
    {
        return $this->version;
    }

    public function getHash(): string
    {
        return $this->hash;
    }

    public function getBlockHash(): string
    {
        return $this->blockHash;
    }

    public function getHeight(): int
    {
        return $this->height;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function getRequestedAmount(): float
    {
        return $this->requestedAmount;
    }

    public function getNotYetPaid(): float
    {
        return $this->notYetPaid;
    }

    public function getUserPaidFee(): float
    {
        return $this->userPaidFee;
    }

    public function getPaymentAddress(): string
    {
        return $this->paymentAddress;
    }

    public function getProposalDuration(): int
    {
        return $this->proposalDuration;
    }

    public function getDuration(): string
    {
        $inputSeconds = $this->proposalDuration;

        $secondsInAMinute = 60;
        $secondsInAnHour = 60 * $secondsInAMinute;
        $secondsInADay = 24 * $secondsInAnHour;
        $secondsInAWeek = 7 * $secondsInADay;
        $secondsInAYear = 52 * $secondsInAWeek;

        // extract years
        $years = floor($inputSeconds / $secondsInAYear);

        // extract months
        $monthSeconds = $inputSeconds % $secondsInAYear;
        $weeks = floor($monthSeconds / $secondsInAWeek);

        // extract days
        $daySeconds = $inputSeconds % $secondsInAWeek;
        $days = floor($daySeconds / $secondsInADay);

        // extract hours
        $hourSeconds = $inputSeconds % $secondsInADay;
        $hours = floor($hourSeconds / $secondsInAnHour);

        // extract minutes
        $minuteSeconds = $hourSeconds % $secondsInAnHour;
        $minutes = floor($minuteSeconds / $secondsInAMinute);

        // extract the remaining seconds
        $remainingSeconds = $minuteSeconds % $secondsInAMinute;
        $seconds = ceil($remainingSeconds);

        $date = "";
        $date .= $years ? $years . ($years == 1 ? ' year, ' : ' years, ') : '';
        $date .= $weeks ? $weeks . ($weeks == 1 ? ' week, ' : ' weeks, ') : '';
        $date .= $days ? $days . ($days == 1 ? ' day, ' : ' days, ') : '';
        $date .= $hours ? $hours . ($hours == 1 ? ' hour, ' : ' hours, ') : '';

        if ($this->proposalDuration < 604800) {
            $date .= $minutes ? $minutes . ($minutes == 1 ? ' minute, ' : ' minutes, ') : '';
            $date .= $seconds ? $seconds . ($seconds == 1 ? ' second, ' : ' seconds, ') : '';
        }

        return trim($date, ', ');
    }

    public function getState(): string
    {
        return $this->state;
    }

    public function getStateChangedOnBlock(): ?string
    {
        return $this->stateChangedOnBlock;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function getExpiresOn(): ?\DateTime
    {
        return $this->expiresOn;
    }

    public function setExpiresOn(\DateTime $expiresOn): self
    {
        $this->expiresOn = $expiresOn;

        return $this;
    }

    public function getVotesYes(): int
    {
        return $this->votesYes;
    }

    public function getVotesAbs(): int
    {
        return $this->votesAbs;
    }

    public function getVotesNo(): int
    {
        return $this->votesNo;
    }

    public function getVotesExcluded(): int
    {
        return $this->votesExcluded;
    }

    public function getVotingCycle(): int
    {
        return $this->votingCycle;
    }

    public function getIsSuper(): bool
    {
        return $this->version & 1<<6;
    }
}

templates/community_fund/components/block_cycle.html.twig
<div class="card">
    <div class="card-body">
        <h4>Accepting a proposal</h4>
        <p>At least {{ blockCycle.minQuorum * 100 }}% of blocks in the cycle must have voted for the proposal.</p>
        <p>At least {{ blockCycle.proposalVoting.accept*100 }}% if those voting blocks must have voted `YES` for the proposal.</p>
        <p>A proposal has {{ blockCycle.proposalVoting.cycles }} full block cycles opportunities to be accepted.</p>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4>Rejecting a proposal</h4>
        <p>At least {{ blockCycle.minQuorum * 100 }}% of blocks in the cycle must have voted for the proposal.</p>
        <p>At least {{ blockCycle.proposalVoting.reject*100 }}% if those voting blocks must have voted `NO` for the proposal.</p>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Voting Rules</h4>
        <h5 class="card-subtitle mb-2">Proposal </h5>

        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a>
    </div>
</div>

templates/community_fund/components/blockcycle_stats.html.twig
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-info">
            Votes counted for block <strong>{{ blockCycle.index|number_format }}</strong> of <strong>{{ blockCycle.size|number_format }}</strong>.<br/>
            {% if blockCycle.remainingBlocks == 1 %}
                There is <strong>{{ blockCycle.remainingBlocks|number_format }}</strong> block remaining in the current cycle.
            {% else %}
                There are <strong>{{ blockCycle.remainingBlocks|number_format }}</strong> blocks remaining in the current cycle.
            {% endif %}
        </div>
    </div>
</div>

templates/community_fund/components/paymentrequest_card.html.twig
<div class="card card-proposal card-nav">
    <div class="card-header" style="{{ paymentRequest.isSuper ? 'background: #4a3a6f !important;  color: #ffffff;' : '' }}">
        <h2 class="clamp" data-lines="3" style="padding: 0px 10px;">{{ paymentRequest.description|capitalize}}</h2>
    </div>

    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Payment Request Hash
                <span class="float-right">
                    <a href="{{ path('app_communityfund_viewpaymentrequest', {'hash': paymentRequest.hash}) }}" class="break-word">
                        {{ paymentRequest.hash[0:10] }}...{{ paymentRequest.hash[paymentRequest.hash|length-4:] }}
                    </a>
                </span>
            </li>
            <li class="list-group-item">
                Nav Requested
                <span class="float-right">{{ paymentRequest.requestedAmount|nav }}</span>
            </li>

            <li class="list-group-item">
                <p>Acceptance</p>
                {{ paymentRequestVoteProgress(paymentRequest, blockCycle) }}

                <p>Participation</p>
                {{ paymentRequestVoteProgressParticipation(paymentRequest, blockCycle) }}

                <p>
                    Accept {{ paymentRequest.votesYes|number_format }} /
                    Reject {{ paymentRequest.votesNo|number_format }} /
                    Abstain {{ paymentRequest.votesAbs|number_format }} /
                    Exclude {{ paymentRequest.votesExcluded|number_format }}
                </p>
                <p>
                    Voting Cycle: {{ paymentRequest.votingCycle }}
                </p>
            </li>

            <li class="list-group-item">
                Status
                <span class="float-right">{{ paymentRequest.status|title }}</span>
            </li>

            <li class="list-group-item">
                Super proposal request
                <span class="float-right">{{ paymentRequest.isSuper ? 'Yes' : 'No' }}</span>
            </li>
        </ul>
    </div>

    <div class="card-footer">
        <div class="d-flex justify-content-center">
            <a href="{{ path('app_communityfund_viewpaymentrequest', {'hash': paymentRequest.hash}) }}">View Payment Request</a>
        </div>
    </div>
</div>

templates/community_fund/components/paymentrequest_card_slim.html.twig
<div class="margin-bottom-half">
    <h5><a href="{{ path('app_communityfund_viewpaymentrequest', {'hash': paymentRequest.hash}) }}" class="break-word">{{ paymentRequest.description|capitalize|default("No Description")}}</a></h5>
</div>

templates/community_fund/components/proposal_card.html.twig
<div class="card card-proposal card-nav">
    <div class="card-header" style="{{ proposal.isSuper ? 'background: #4a3a6f !important;  color: #ffffff;' : '' }}">
        <h2 class="clamp" data-lines="3" style="padding: 0px 10px;">{{ proposal.description|capitalize}}</h2>
    </div>

    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Proposal Hash
                <span class="float-right">
                    <a href="{{ path('app_communityfund_view', {'hash': proposal.hash}) }}" class="break-word">
                        {{ proposal.hash[0:10] }}...{{ proposal.hash[proposal.hash|length-4:] }}
                    </a>
                </span>
            </li>
            <li class="list-group-item">
                Nav Requested
                <span class="float-right">{{ proposal.requestedAmount|nav }}</span>
            </li>
            <li class="list-group-item">
                Nav Paid
                <span class="float-right">{{ (proposal.requestedAmount - proposal.notYetPaid)|nav }}</span>
            </li>
            <li class="list-group-item">
                Duration
                <span class="float-right">{{ proposal.duration }}</span>
            </li>
            <li class="list-group-item">
                <p>Acceptance</p>
                {{ proposalVoteProgress(proposal, blockCycle) }}

                <p>Participation</p>
                {{ proposalVoteProgressParticipation(proposal, blockCycle) }}

                <p>
                    Accept {{ proposal.votesYes|number_format }} /
                    Reject {{ proposal.votesNo|number_format }} /
                    Abstain {{ proposal.votesAbs|number_format }} /
                    Exclude {{ proposal.votesExcluded|number_format }}
                </p>
                <p>Voting Cycle: {{ proposal.votingCycle }}</p>
            </li>
            <li class="list-group-item">
                Status
                <span class="float-right">{{ proposal.status|title }}</span>
            </li>
            <li class="list-group-item">
                Super proposal
                <span class="float-right">{{ proposal.isSuper ? 'Yes' : 'No' }}</span>
            </li>
        </ul>
    </div>

    <div class="card-footer">
        <div class="d-flex justify-content-around">
            <a href="{{ path('app_communityfund_view', {'hash': proposal.hash}) }}">View Proposal</a>
        </div>
    </div>
</div>

templates/community_fund/components/proposal_card_slim.html.twig
<div class="margin-bottom-half">
        <h5><a href="{{ path('app_communityfund_view', {'hash': proposal.hash}) }}" class="break-word">{{ proposal.description|capitalize|default("No Description")}}</a></h5>

</div>

templates/community_fund/components/view_payment_requests.html.twig
<div class="row">
    {% for paymentRequest in paymentRequests %}
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="card card-proposal card-nav">
                <div class="card-header" style="{{ paymentRequest.isSuper ? 'background: #4a3a6f !important;  color: #ffffff;' : '' }}">
                    <h2 class="clamp" data-lines="3" style="padding: 0px 10px;">{{ paymentRequest.description|capitalize}}</h2>
                </div>

                <div class="card-body">
                    <ul class="list-group list-group-flush">

                        <li class="list-group-item">
                            Payment Request Hash
                            <span class="float-right">
                                <a href="{{ path('app_communityfund_viewpaymentrequest', {'hash': paymentRequest.hash}) }}" class="break-word">
                                    {{ paymentRequest.hash[0:10] }}...{{ paymentRequest.hash[paymentRequest.hash|length-4:] }}
                                </a>
                            </span>
                        </li>

                        <li class="list-group-item">
                            Nav&nbsp;Requested
                            <span class="float-right">{{ paymentRequest.requestedAmount|nav }}</span>
                        </li>

                        <li class="list-group-item">
                            <p>Acceptance</p>
                            {{ paymentRequestVoteProgress(paymentRequest, blockCycle) }}

                            <p>Participation</p>
                            {{ paymentRequestVoteProgressParticipation(paymentRequest, blockCycle) }}

                            <p class="text-muted">
                            <span class="float-left">
                                Accept {{ paymentRequest.votesYes }} / Reject {{ paymentRequest.votesNo }}
                            </span>
                                <span class="float-right">Cycle: {{ paymentRequest.votingCycle }}</span>
                            </p>
                        </li>

                        <li class="list-group-item">
                            Status
                            <span class="float-right">{{ paymentRequest.status|capitalize }}</span>
                        </li>
                        <li class="list-group-item">
                            Super proposal request
                            <span class="float-right">{{ paymentRequest.isSuper ? 'Yes' : 'No' }}</span>
                        </li>
                    </ul>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center">
                        <a href="{{ path('app_communityfund_viewpaymentrequest', {'hash': paymentRequest.hash}) }}">View Payment Request</a>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="col-md-12">
            <p>No payment requests have been made for this proposal</p>
        </div>
    {% endfor %}
</div>

templates/community_fund/components/view_proposal_details.html.twig
<div class="row summary">
    <div class="col-md-8">
        <table class="table table-striped table-nav">
            <tbody>
            <tr>
                <td colspan="2" class="proposal-description">
                    {{ proposal.description }}
                </td>
            </tr>
            <tr>
                <th>Proposal Hash</th>
                <td class="text-right break-word" id="proposal-hash" data-hash="{{ proposal.hash }}">
                    {{ proposal.hash[0:20] }}...{{ proposal.hash[proposal.hash|length-4:] }}
                </td>
            </tr>
            <tr>
                <th>Block&nbsp;Hash</th>
                <td class="text-right break-word">
                    <a href="{{ path('app_block_view', {'height': proposal.blockHash}) }}">
                        {{ proposal.blockHash[0:20] }}...{{ proposal.blockHash[proposal.blockHash|length-4:] }}
                    </a>
                </td>
            </tr>
            <tr>
                <th>Payment&nbsp;Address</th>
                <td class="text-right break-word">
                    <a href="{{ path('app_address_index', {'hash': proposal.paymentAddress}) }}">{{ proposal.paymentAddress }}</a>
                </td>
            </tr>
            <tr>
                <th>Duration</th>
                <td class="text-right break-word">
                    {{ proposal.duration }}
                </td>
            </tr>
            {% if proposal.expiresOn %}
                <tr>
                    <th>Expiry Date</th>
                    <td class="text-right break-word">{{ proposal.expiresOn|date_localised('Y-m-d, H:i:s') }}</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>

    <div class="col-md-4">
        <table class="table table-striped table-nav table-second">
            <tbody>
            <tr>
                <th>Nav&nbsp;Requested</th>
                <td class="text-right break-word">{{ proposal.requestedAmount|nav }}</td>
            </tr>
            <tr>
                <th>Nav&nbsp;Paid</th>
                <td class="text-right break-word">{{ (proposal.requestedAmount - proposal.notYetPaid)|nav }}</td>
            </tr>
            <tr>
                <th>Fee</th>
                <td class="text-right break-word">{{ proposal.userPaidFee|nav }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td class="text-right break-word">{{ proposal.status|title }}</td>
            </tr>
            <tr>
                <th>Super proposal</th>
                <td class="text-right break-word proposal-super">{{ proposal.isSuper ? 'Yes' : 'No' }}</td>
            </tr>

            {% if proposal.stateChangedOnBlock and proposal.state == "ACCEPTED" %}
                <tr>
                    <th>Acception Date</th>
                    <td class="text-right break-word">
                        {{ block.created|date_localised('Y-m-d, H:i:s') }}
                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>

    </div>
</div>